library(shiny)
library(plotly)
library(shinythemes)
library(ggplot2)
library(DT)
library(pheatmap)
library(threejs)
library(sm)
library(RColorBrewer)
library(mclust)
library(reshape)
library(edgeR)

source("utils.R")
source("plots.R")

sapply(list.files("modules/ui", full.names=T), source)
sapply(list.files("modules/backend", full.names=T), source)
